Add Traditional Chinese `zh_tw.json`
nonamecrackers2/simple-clouds pull request #32
Opened 2024-10-20 18:33 UTC by yichifauzi

Add Traditional Chinese localization

2024-10-26 08:04 UTC, notlin4 requested changes
Fix traditional Chinese localization

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.clientSideCloudHeight.description": "指定雲的繪製 Y 偏移量。\n範圍：0 ~ 2048",
```suggestion
  "gui.simpleclouds.config.clientSideCloudHeight.description": "指定雲的顯示 Y 偏移量。\n範圍：0 ~ 2048",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.height.get": "雲高度已設定為 %s",
```suggestion
  "command.simpleclouds.height.get": "雲的高度為 %s",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.height.set": "將雲高度設定為 %s",
```suggestion
  "command.simpleclouds.height.set": "已將雲的高度設為 %s",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.reinitialize": "雲已重置",
```suggestion
  "command.simpleclouds.reinitialize": "雲已重設",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.seed.get": "目前的雲種子為 %s",
```suggestion
  "command.simpleclouds.seed.get": "目前雲的種子碼為 %s",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.scroll.get": "目前的雲捲動位置為 [x: %s, y: %s, z: %s]",
```suggestion
  "command.simpleclouds.scroll.get": "目前雲的捲動位置為 [x: %s, y: %s, z: %s]",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.speed.get": "目前的雲速度為 %s",
```suggestion
  "command.simpleclouds.speed.get": "目前雲的速度為 %s",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.renderClouds.description": "切換雲的繪製。",
```suggestion
  "gui.simpleclouds.config.renderClouds.description": "切換雲的顯示。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.renderClouds.title": "繪製雲",
```suggestion
  "gui.simpleclouds.config.renderClouds.title": "顯示雲",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.renderStormFog.title": "繪製暴風雨迷霧",
```suggestion
  "gui.simpleclouds.config.renderStormFog.title": "顯示暴風雨迷霧",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.singleModeFadeEndPercentage.description": "指定使用單一雲類型模式時雲將完全淡出的雲繪製距離百分比（例如：50 將使雲在超過雲繪製距離一半後完全消失）。\n範圍：0 ~ 100",
```suggestion
  "gui.simpleclouds.config.singleModeFadeEndPercentage.description": "指定使用單一雲類型模式時雲將完全淡出雲的顯示距離百分比（例如：50 將使雲在超過雲顯示距離一半後完全消失）。\n範圍：0 ~ 100",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.singleModeFadeStartPercentage.description": "指定使用單一雲類型模式時雲應開始淡出的雲繪製距離百分比（例如：50 將在雲繪製距離的一半處開始使雲淡出）。\n範圍：0 ~ 100",
```suggestion
  "gui.simpleclouds.config.singleModeFadeStartPercentage.description": "指定使用單一雲類型模式時雲應開始淡出的雲顯示距離百分比（例如：50 將在雲顯示距離的一半處開始使雲淡出）。\n範圍：0 ~ 100",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.cloudSeed.title": "雲種子",
```suggestion
  "gui.simpleclouds.config.cloudSeed.title": "雲的種子碼",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.cloudMode.title": "雲模式",
```suggestion
  "gui.simpleclouds.config.cloudMode.title": "雲的模式",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.cloudSeed.description": "指定用於雲的種子。將套用於僅用戶端安裝了模組的使用者連線的所有伺服器。",
```suggestion
  "gui.simpleclouds.config.cloudSeed.description": "指定用於雲的種子碼。只要用戶端安裝這個模組，連線到任何伺服器都會套用此設定。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.cloudStyle.description": "指定雲的視覺樣式。預設為預設樣式。陰影為雲新增最少的陰影，使它們看起來更清晰。",
```suggestion
  "gui.simpleclouds.config.cloudStyle.description": "指定雲的視覺樣式。預設為預設樣式。陰影為雲新增最少的陰影，使其看起來更清晰。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.fogMode.description": "指定應使用的世界迷霧類型。每種都有自己的優缺點，從視覺差異到可能的相容性問題。",
```suggestion
  "gui.simpleclouds.config.fogMode.description": "指定應使用的世界迷霧類型。每種類型都有自身的優缺點，從視覺差異到可能的相容性問題。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.framesToGenerateMesh.title": "生成網格的幀數",
```suggestion
  "gui.simpleclouds.config.framesToGenerateMesh.title": "生成網格的影格數",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.useSpecificSeed.description": "指定是否應使用「雲種子」選項設定的種子。",
```suggestion
  "gui.simpleclouds.config.useSpecificSeed.description": "指定是否應使用「雲的種子碼」選項設定的種子碼。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.error.recommendations": "請嘗試更新您的顯示卡驅動程式。如果問題仍然存在，請在下方連結的簡易雲儲存庫上提交錯誤記錄檔。提交問題時，請務必附上崩潰記錄檔。\n\n請注意，簡易雲僅支援支援 OpenGL 4.3+ 的 GPU。如果您已更新顯示卡驅動程式，但此問題仍然存在，則可能是您的顯示卡太舊而無法支援簡易雲。",
```suggestion
  "gui.simpleclouds.error.recommendations": "請嘗試更新您的顯示卡驅動程式。如果問題仍然存在，請在下方連結的 Simple Clouds 儲存庫上回報錯誤。回報錯誤時，請務必附上崩潰報告。\n\n請注意，Simple Clouds 僅支援 OpenGL 4.3+ 的 GPU。如果您已更新顯示卡驅動程式，但此問題仍然存在，則可能是您的顯示卡太舊，而無法支援 Simple Clouds。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.error_screen.title": "簡易雲錯誤",
```suggestion
  "gui.simpleclouds.error_screen.title": "Simple Clouds 發生錯誤",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.requires_reload.info": "修改了一個設定檔選項，需要重新載入雲繪製器。您要重新載入繪製器以套用變更嗎？",
```suggestion
  "gui.simpleclouds.requires_reload.info": "修改的設定選項需要重新載入雲渲染器。您要重新載入渲染器以套用變更嗎？",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.reload_confirmation.server.info": "伺服器上修改了一個設定檔選項，需要重新載入雲繪製器。請按「繼續」繼續。",
```suggestion
  "gui.simpleclouds.reload_confirmation.server.info": "伺服器上修改的設定選項需要重新載入雲渲染器。請按「繼續」繼續。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "simpleclouds.key.categories.main": "Simple Clouds《簡易雲》",
```suggestion
  "simpleclouds.key.categories.main": "Simple Clouds",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.error.unknown": "請在下方連結的模組 GitHub 儲存庫上提交錯誤記錄檔。提交問題時，請務必附上崩潰記錄檔和 latest.log 檔案。",
```suggestion
  "gui.simpleclouds.error.unknown": "請在下方連結模組的 GitHub 儲存庫上回報錯誤。回報錯誤時，請務必附上崩潰報告和 latest.log 檔案。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.unknown_or_invalid_client_side_cloud_type.info": "未知或無效的雲類型 '%s'。請選擇有效的雲類型。 \n\n有效的雲類型如下：\n\n%s",
```suggestion
  "gui.simpleclouds.unknown_or_invalid_client_side_cloud_type.info": "未知或無效的雲類型 '%s'。請選擇有效的雲類型。\n\n有效的雲類型如下：\n\n%s",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "command.simpleclouds.weather.override": "簡易雲正在覆蓋原版天氣，且 /weather 指令已被停用。要使用原版天氣，請執行以下任一操作：\n1. 將伺服器設定檔中的雲模式設定為環境。\n2. 將伺服器設定檔中的雲模式設定為單一，並將單一模式雲類型設定為沒有關聯天氣的雲類型（例如：simpleclouds:itty_bitty）",
```suggestion
  "command.simpleclouds.weather.override": "Simple Clouds 正在覆蓋原版天氣，且 /weather 指令已被停用。要使用原版天氣，請執行以下任一操作：\n1. 將伺服器設定檔中的雲模式設定為環境。\n2. 將伺服器設定檔中的雲模式設為單一，並將單一模式雲類型設定為沒有關聯天氣的雲類型（例如：simpleclouds:itty_bitty）",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "commands.simpleclouds.client.configReferal": "此選項已被用戶端設定檔覆蓋。請參閱用戶端設定檔來更改此選項。",
```suggestion
  "commands.simpleclouds.client.configReferal": "此選項已被用戶端設定檔覆蓋。請參閱用戶端設定檔來變更此選項。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "commands.simpleclouds.notClientSideOnly": "用戶端雲指令只能在連線到未安裝簡易雲的伺服器時使用。如果您連線到單人遊戲，或者您是在安裝了簡易雲的專用伺服器上的管理員，請使用 '/simpleclouds clouds'",
```suggestion
  "commands.simpleclouds.notClientSideOnly": "用戶端雲指令只能在連線到未安裝 Simple Clouds 的伺服器時使用。如果您連線到單人遊戲，或者您是在安裝了 Simple Clouds 的專用伺服器上的管理員，請使用 '/simpleclouds clouds'",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.clientSideCloudMode.description": "指定雲在僅用戶端環境中的行為方式。單一模式僅使用單一雲類型。環境模式會在玩家周圍雕刻雲，使它們保持一定距離。由於僅在用戶端環境中，因此無法選擇預設模式，將會使用原版天氣系統。如果伺服器上安裝了簡易雲，則會忽略此選項，用戶端將改用伺服器設定的選項。",
```suggestion
  "gui.simpleclouds.config.clientSideCloudMode.description": "指定雲在僅用戶端環境中的行為方式。單一模式僅使用單一雲類型。環境模式會在玩家周圍雕刻雲，使它們保持一定距離。由於僅在用戶端環境中，因此無法選擇預設模式，將會使用原版天氣系統。如果伺服器上安裝了 Simple Clouds，則會忽略此選項，用戶端將改用伺服器設定的選項。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.cloudMode.description": "指定雲的行為方式。預設模式使用所有雲類型和簡易雲中的預設天氣。單一模式僅使用單一雲類型及其關聯天氣。環境模式停用局部天氣並在玩家周圍雕刻雲，使它們保持一定距離。",
```suggestion
  "gui.simpleclouds.config.cloudMode.description": "指定雲的行為方式。預設模式使用所有雲類型和 Simple Clouds 中的預設天氣。單一模式僅使用單一雲類型及其關聯天氣。環境模式停用局部天氣並在玩家周圍雕刻雲，使它們保持一定距離。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.dimensionWhitelist.description": "指定簡易雲啟用的允許維度",
```suggestion
  "gui.simpleclouds.config.dimensionWhitelist.description": "指定 Simple Clouds 啟用的允許維度",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.debug.title": "簡易雲除錯",
```suggestion
  "gui.simpleclouds.debug.title": "Simple Clouds 除錯",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.useSpecificSeed.title": "使用特定種子",
```suggestion
  "gui.simpleclouds.config.useSpecificSeed.title": "使用特定種子碼",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.config.category.seed.title": "種子",
```suggestion
  "gui.simpleclouds.config.category.seed.title": "種子碼",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.error.couldNotLoadMeshScript": "無法載入網格計算著色器。請在下方連結的模組 GitHub 儲存庫上提交錯誤記錄檔。提交問題時，請務必附上崩潰記錄檔和 latest.log 檔案。\n\n致開發人員：如果您使用資源包修改 cube_mesh.comp 檔案並發生錯誤，則啟動時將會出現此訊息。請參閱 latest.log 以取得
```suggestion
  "gui.simpleclouds.error.couldNotLoadMeshScript": "無法載入網格計算著色器。請在下方連結的模組 GitHub 儲存庫上回報錯誤。回報錯誤時，請務必附上崩潰報告和 latest.log 檔案。\n\n致開發人員：如果您使用資源包修改 cube_mesh.comp 檔案並發生錯誤，則啟動時將會出現此訊息。請參閱 latest.log 以取得更多詳細資訊。",
```

2024-10-26 08:04 UTC, notlin4 commented on src/main/resources/assets/simpleclouds/lang/zh_tw.json
> +  "gui.simpleclouds.error_screen.button.crash_report": "崩潰回報",
```suggestion
  "gui.simpleclouds.error_screen.button.crash_report": "崩潰報告",
```

2025-06-23 00:52 UTC, nonamecrackers2 approved these changes

2025-06-23 00:52 UTC, merged